const mongoose = require('mongoose');
var dataTables = require('mongoose-datatables')
const game_running_roulette_schema = new mongoose.Schema({
     RoundCount:Number,
     playername:String,
    straightUp:String,
    Split:String,
    Street:String,
    Corner:String,
    specificBet:String,
    line:String,
    dozen1:String,
    dozen2:String,
    dozen3:String,
    column1:String,
    column2:String,
    column3:String,
    onetoEighteen:String,
    nineteentoThirtysix:String,
    even:String,
    odd:String,
    black:String,
    red:String,
    straightUpVal:String,
    SplitVal:String,
    StreetVal:String,
    CornerVal:String,
    specificBetVal:String,
    lineVal:String,
    dozen1Val:String,
    dozen2Val:String,
    dozen3Val:String,
    column1Val:String,
    column2Val:String,
    column3Val:String,
    onetoEighteenVal:String,
    nineteentoThirtysixVal:String,
    evenVal:String,
    oddVal:String,
    blackVal:String,
    redVal:String,
    winpoint:Number,
    betpoint:Number,
    Win_singleNo:Number,
    idManager:String,
    playedTime:{type:Date },

});

game_running_roulette_schema.plugin(dataTables)
module.exports = mongoose.model('game_running_roulette', game_running_roulette_schema);
